import type { PiAgentClient } from '../client';
import { formatThread, type GitHubThreadContext, type IssueReadinessResult, type IssueReadinessStatus } from './types';

const statuses: IssueReadinessStatus[] = ['needs-refinement', 'needs-approval', 'ready-for-agent'];

function extractJson(text: string) {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1];
  if (fenced) return fenced.trim();
  const start = text.indexOf('{');
  const end = text.lastIndexOf('}');
  if (start >= 0 && end > start) return text.slice(start, end + 1);
  return text;
}

function toStringArray(value: unknown) {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string' && item.trim().length > 0) : [];
}

export function parseIssueReadinessResult(text: string): IssueReadinessResult {
  const parsed = JSON.parse(extractJson(text)) as Partial<IssueReadinessResult>;
  if (!statuses.includes(parsed.status as IssueReadinessStatus)) throw new Error('Pi Agent returned an invalid readiness status.');
  if (typeof parsed.summary !== 'string' || !parsed.summary.trim()) throw new Error('Pi Agent returned an invalid readiness summary.');
  const reasons = toStringArray(parsed.reasons);
  if (!reasons.length) throw new Error('Pi Agent returned no readiness reasons.');
  const recommendations = toStringArray(parsed.recommendations);
  return { status: parsed.status as IssueReadinessStatus, summary: parsed.summary, reasons, ...(recommendations.length ? { recommendations } : {}) };
}

export function formatIssueReadinessComment(result: IssueReadinessResult) {
  const label = result.status === 'ready-for-agent' ? 'Ready for agent' : result.status === 'needs-approval' ? 'Needs approval' : 'Needs refinement';
  const recommendations = result.recommendations?.length
    ? `\n\n**Recommendations**\n${result.recommendations.map((item) => `- ${item}`).join('\n')}`
    : '';
  return `## Pi Agent issue readiness: ${label}\n\n**Status:** \`${result.status}\`\n\n**Summary**\n${result.summary}\n\n**Reasons**\n${result.reasons.map((item) => `- ${item}`).join('\n')}${recommendations}\n\n---\n_Generated by Pi Agent._`;
}

export async function analyzeIssueReadiness(client: PiAgentClient, ctx: GitHubThreadContext): Promise<IssueReadinessResult> {
  const result = await client.run({
    action: 'analyze-issue-readiness',
    messages: [
      {
        role: 'system',
        content: 'You evaluate GitHub issue readiness for an autonomous coding agent. Return only strict JSON with keys status, summary, reasons, recommendations. Status must be one of: needs-refinement, needs-approval, ready-for-agent.',
      },
      {
        role: 'user',
        content: `Analyze this loaded GitHub issue context. Choose:\n- needs-refinement: requirements, reproduction, acceptance criteria, or scope are unclear.\n- needs-approval: implementation is clear enough but needs human/product approval or prioritization.\n- ready-for-agent: scope and acceptance criteria are clear enough for a coding agent to start.\n\nReturn strict JSON only, matching this TypeScript shape: {"status":"needs-refinement"|"needs-approval"|"ready-for-agent","summary":"string","reasons":["string"],"recommendations":["string"]}.\n\n${formatThread(ctx)}`,
      },
    ],
    metadata: { target: ctx },
  });
  return parseIssueReadinessResult(result.text);
}
