import { Button, Link } from '@kobalte/core';
import { For, Show, createMemo, createSignal, onCleanup, onMount } from 'solid-js';
import { fetchAgentInvocations, loadAgentInvocations, type AgentInvocation } from '../lib/agent-activity';

type MentionStatus = 'new' | 'acknowledged' | 'resolved' | 'ignored';
type Mention = { id: string; status: MentionStatus; owner: string; repo: string; thread_kind: 'issue' | 'pull'; thread_number: number; thread_title: string; thread_url: string; source_type: string; source_url: string; author_login?: string | null; body_snippet?: string | null; first_detected_at: string; source_created_at: string };

function relativeDate(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function targetLabel(invocation: AgentInvocation) { const t = invocation.target; if (t.owner && t.repo && t.number) return `${t.owner}/${t.repo}#${t.number}`; if (t.owner && t.repo) return `${t.owner}/${t.repo}`; return t.title ?? 'Unknown target'; }
function targetHref(invocation: AgentInvocation) { const t = invocation.target; if (t.kind === 'issue' && t.owner && t.repo && t.number) return `/repos/${encodeURIComponent(t.owner)}/${encodeURIComponent(t.repo)}/issues/${t.number}`; if (t.url) return t.url; return undefined; }
async function mentionsRequest(body?: unknown, status?: string) { const res = await fetch(body ? '/api/mentions' : `/api/mentions${status ? `?status=${status}` : ''}`, body ? { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) } : undefined); const payload = await res.json().catch(() => ({})); if (!res.ok) throw new Error(payload.error ?? 'Mentions request failed.'); return payload; }

export default function AgentPage() {
  const [invocations, setInvocations] = createSignal<AgentInvocation[]>([]);
  const [error, setError] = createSignal<string | null>(null);
  const [loading, setLoading] = createSignal(true);
  const [mentions, setMentions] = createSignal<Mention[]>([]);
  const [mentionError, setMentionError] = createSignal<string | null>(null);
  const [pollErrors, setPollErrors] = createSignal<Array<{ repo: string; error: string }>>([]);
  const [polling, setPolling] = createSignal(false);
  const [status, setStatus] = createSignal<MentionStatus | 'all'>('new');

  async function refresh() { setLoading(true); setError(null); try { setInvocations(await fetchAgentInvocations()); } catch (err) { setError(err instanceof Error ? err.message : 'Failed to load agent activity.'); setInvocations(loadAgentInvocations()); } finally { setLoading(false); } }
  async function loadMentions() { setMentionError(null); try { const payload = await mentionsRequest(undefined, status() === 'all' ? undefined : status()); setMentions(payload.items ?? []); } catch (err) { setMentionError(err instanceof Error ? err.message : 'Failed to load mentions.'); } }
  async function pollMentions() { setPolling(true); setMentionError(null); try { const payload = await mentionsRequest({ action: 'poll' }); setMentions(status() === 'all' ? (payload.items ?? []) : (payload.items ?? []).filter((m: Mention) => m.status === status())); setPollErrors(payload.errors ?? []); } catch (err) { setMentionError(err instanceof Error ? err.message : 'Failed to poll mentions.'); } finally { setPolling(false); } }
  async function setMentionStatus(id: string, next: MentionStatus) { await mentionsRequest({ action: 'status', id, status: next }); await loadMentions(); }

  onMount(() => { void refresh(); void pollMentions(); const interval = window.setInterval(() => void pollMentions(), 30_000); const sync = () => void refresh(); window.addEventListener('agent-invocations-changed', sync); window.addEventListener('storage', sync); onCleanup(() => { window.clearInterval(interval); window.removeEventListener('agent-invocations-changed', sync); window.removeEventListener('storage', sync); }); });
  const stats = createMemo(() => ({ total: invocations().length, succeeded: invocations().filter((i) => i.status === 'succeeded').length, failed: invocations().filter((i) => i.status === 'failed').length }));

  return <main class="min-h-screen bg-surface px-6 py-8 text-neutral-950 dark:bg-neutral-950 dark:text-neutral-100"><section class="mx-auto max-w-6xl space-y-8">
    <div class="flex flex-wrap items-end justify-between gap-3"><div><p class="text-sm font-medium text-neutral-500">Pi Agent</p><h1 class="text-3xl font-semibold">Agent</h1><p class="mt-1 max-w-2xl text-neutral-600 dark:text-neutral-300">Mentions inbox for @randy-helper plus local agent workflow activity.</p></div><div class="flex gap-2"><Link.Root class="rounded-lg border border-neutral-300 px-3 py-2 text-sm font-medium dark:border-neutral-700" href="/">Home</Link.Root><Button.Root class="rounded-lg border border-neutral-300 px-3 py-2 text-sm font-medium disabled:opacity-50 dark:border-neutral-700" disabled={polling()} onClick={pollMentions}>{polling() ? 'Polling…' : 'Poll mentions'}</Button.Root></div></div>

    <section class="space-y-3"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="text-2xl font-semibold">Mentions inbox</h2><div class="flex flex-wrap gap-2"><For each={['all', 'new', 'acknowledged', 'resolved', 'ignored'] as const}>{(s) => <Button.Root class={`rounded-lg border px-3 py-1.5 text-sm ${status() === s ? 'bg-neutral-950 text-white dark:bg-white dark:text-neutral-950' : 'border-neutral-300 dark:border-neutral-700'}`} onClick={() => { setStatus(s); void loadMentions(); }}>{s}</Button.Root>}</For></div></div>
      <Show when={mentionError()}>{(m) => <p class="rounded-xl border border-red-200 bg-red-50 p-3 text-red-700">{m()}</p>}</Show>
      <Show when={pollErrors().length}><div class="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><p class="font-medium">Some repositories failed:</p><For each={pollErrors()}>{(e) => <p>{e.repo}: {e.error}</p>}</For></div></Show>
      <Show when={mentions().length} fallback={<div class="mystery-card p-6 text-neutral-500">No mentions for this filter. Favorite repositories on the Repositories page, then poll.</div>}><ol class="mystery-card divide-y dark:divide-neutral-800"><For each={mentions()}>{(m) => <li class="p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2 text-xs"><span class="rounded-full border px-2.5 py-1 font-semibold uppercase">{m.status}</span><span>{m.owner}/{m.repo}#{m.thread_number}</span><span>{m.source_type}</span><span>by {m.author_login ?? 'unknown'}</span></div><h3 class="mt-2 font-semibold">{m.thread_title}</h3><p class="mt-1 text-sm text-neutral-600 dark:text-neutral-300">{m.body_snippet}</p><div class="mt-3 flex flex-wrap gap-3 text-sm"><Link.Root class="underline" href={m.thread_kind === 'issue' ? `/repos/${encodeURIComponent(m.owner)}/${encodeURIComponent(m.repo)}/issues/${m.thread_number}` : m.thread_url} target={m.thread_kind === 'pull' ? '_blank' : undefined}>Local thread</Link.Root><Link.Root class="underline" href={m.source_url} target="_blank">GitHub source</Link.Root></div></div><div class="flex flex-col items-end gap-2"><time class="text-sm text-neutral-500">{relativeDate(m.first_detected_at)}</time><div class="flex gap-2"><Button.Root class="rounded border px-2 py-1 text-xs" onClick={() => setMentionStatus(m.id, 'acknowledged')}>Acknowledge</Button.Root><Button.Root class="rounded border px-2 py-1 text-xs" onClick={() => setMentionStatus(m.id, 'resolved')}>Resolve</Button.Root><Button.Root class="rounded border px-2 py-1 text-xs" onClick={() => setMentionStatus(m.id, 'ignored')}>Ignore</Button.Root></div></div></div></li>}</For></ol></Show>
    </section>

    <section class="space-y-4"><h2 class="text-2xl font-semibold">Agent activity</h2><div class="grid gap-3 sm:grid-cols-3"><Stat label="Total runs" value={String(stats().total)} /><Stat label="Succeeded" value={String(stats().succeeded)} /><Stat label="Failed" value={String(stats().failed)} /></div><Show when={error()}>{(m) => <p class="rounded-xl border border-amber-200 bg-amber-50 p-3 text-amber-800">{m()} Showing browser-local fallback activity, if any.</p>}</Show><Show when={!loading()} fallback={<div class="mystery-card p-6 text-neutral-500">Loading agent activity…</div>}><Show when={invocations().length > 0} fallback={<div class="mystery-card p-6 text-neutral-500">No agent activity yet.</div>}><ol class="mystery-card divide-y dark:divide-neutral-800"><For each={invocations()}>{(invocation) => <li class="p-5"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="flex flex-wrap items-center gap-2"><span class="rounded-full border px-2.5 py-1 text-xs font-semibold uppercase">{invocation.agent} agent</span><span class="rounded-full border px-2.5 py-1 text-xs">{invocation.status}</span></div><h3 class="mt-3 text-lg font-semibold">{invocation.workflow}</h3><p class="mt-1 text-sm text-neutral-600 dark:text-neutral-300">{invocation.summary ?? 'No summary captured.'}</p><div class="mt-3 flex flex-wrap gap-3 text-sm"><Show when={targetHref(invocation)} fallback={<span class="text-neutral-500">{targetLabel(invocation)}</span>}>{(href) => <Link.Root class="font-medium underline" href={href()}>{targetLabel(invocation)}</Link.Root>}</Show><Show when={invocation.commentUrl}><Link.Root class="font-medium underline" href={invocation.commentUrl ?? ''} target="_blank">GitHub comment</Link.Root></Show></div></div><time class="text-sm text-neutral-500" dateTime={invocation.ranAt}>{relativeDate(invocation.ranAt)}</time></div></li>}</For></ol></Show></Show></section>
  </section></main>;
}
function Stat(props: { label: string; value: string }) { return <div class="mystery-card p-4"><p class="text-xs uppercase tracking-wide text-neutral-500">{props.label}</p><p class="mt-1 text-2xl font-semibold">{props.value}</p></div>; }
